#!/usr/bin/env bash
# Automatic labels of a pull request, run by .github/workflows/auto-label.yml after the path-based labeler.
#
#   type:           from the Conventional Commit title (feat -> "type: feature", fix -> "type: bug", ...)
#   breaking change from `type(scope)!:` in the title
#   size:           from the number of changed lines, generated files excluded
#   llm-generated   when the Definition of Done box of the PR template is ticked (never removed automatically)
#   needs-tests     code changed but no test file touched          (added and removed automatically)
#   needs-docs      a feature changed code but not docs/ or .dev/  (added and removed automatically)
#
# Environment: GH_TOKEN, REPO (owner/name), PR_NUMBER, PR_TITLE, PR_BODY.
# PR_TITLE and PR_BODY are user input: they are only ever read as data, never evaluated.
set -euo pipefail

current="$(gh pr view "$PR_NUMBER" --repo "$REPO" --json labels --jq '.labels[].name')"
has() { grep -Fxq -- "$1" <<<"$current"; }

add=()
remove=()
want() { if ! has "$1"; then add+=("$1"); fi; }
unwant() { if has "$1"; then remove+=("$1"); fi; }
set_if() { if [[ "$1" == "true" ]]; then want "$2"; else unwant "$2"; fi; }

# --- type and breaking change --------------------------------------------------------------------------------------
commit_type=""
breaking=false
title_re='^([a-z]+)(\([^)]*\))?(!)?:'
if [[ "$PR_TITLE" =~ $title_re ]]; then
  commit_type="${BASH_REMATCH[1]}"
  if [[ -n "${BASH_REMATCH[3]}" ]]; then breaking=true; fi
fi

case "$commit_type" in
  feat) type_label="type: feature" ;;
  fix) type_label="type: bug" ;;
  docs) type_label="type: docs" ;;
  refactor) type_label="type: refactor" ;;
  perf) type_label="type: perf" ;;
  test) type_label="type: test" ;;
  build) type_label="type: build" ;;
  ci) type_label="type: ci" ;;
  chore | style | revert) type_label="type: chore" ;;
  *) type_label="" ;;
esac

if [[ -n "$type_label" ]]; then
  for label in "type: feature" "type: bug" "type: docs" "type: refactor" "type: perf" "type: test" \
    "type: build" "type: ci" "type: chore"; do
    if [[ "$label" == "$type_label" ]]; then want "$label"; else unwant "$label"; fi
  done
fi
set_if "$breaking" "breaking change"

# --- size, tests and docs ------------------------------------------------------------------------------------------
changed=0
code=false
tests=false
docs=false
while IFS=$'\t' read -r file additions deletions; do
  if [[ -z "$file" ]]; then continue; fi
  case "$file" in
    # Generated or lock files do not say anything about the size of a review.
    package-lock.json | CHANGELOG.md | src/lib/database.types.ts | .release-please-manifest.json) continue ;;
  esac
  changed=$((changed + additions + deletions))
  case "$file" in
    *.test.ts | *.test.tsx | supabase/tests/* | e2e/*) tests=true ;;
    docs/* | .dev/* | CLAUDE.md | AGENTS.md | README.md) docs=true ;;
    src/*.ts | src/*.tsx | supabase/migrations/*) code=true ;;
  esac
done < <(gh api "repos/$REPO/pulls/$PR_NUMBER/files" --paginate \
  --jq '.[] | [.filename, .additions, .deletions] | @tsv')

if ((changed < 10)); then
  size="XS"
elif ((changed < 50)); then
  size="S"
elif ((changed < 150)); then
  size="M"
elif ((changed < 400)); then
  size="L"
else
  size="XL"
fi
for candidate in XS S M L XL; do
  if [[ "$candidate" == "$size" ]]; then want "size: $candidate"; else unwant "size: $candidate"; fi
done

needs_tests=false
if $code && ! $tests && [[ "$commit_type" =~ ^(feat|fix|perf)$ ]]; then needs_tests=true; fi
set_if "$needs_tests" "needs-tests"

needs_docs=false
if $code && ! $docs && [[ "$commit_type" == "feat" ]]; then needs_docs=true; fi
set_if "$needs_docs" "needs-docs"

# --- LLM disclosure (checkbox of the PR template) ------------------------------------------------------------------
llm_re='^[[:space:]]*-[[:space:]]\[[xX]\][[:space:]]+This PR was \(partly\) generated by an LLM'
if grep -Eq "$llm_re" <<<"$PR_BODY"; then
  want "llm-generated"
fi

# --- apply ---------------------------------------------------------------------------------------------------------
args=()
for label in ${add[@]+"${add[@]}"}; do args+=(--add-label "$label"); done
for label in ${remove[@]+"${remove[@]}"}; do args+=(--remove-label "$label"); done

if ((${#args[@]} == 0)); then
  echo "Labels already up to date."
else
  echo "add: ${add[*]-} | remove: ${remove[*]-}"
  gh pr edit "$PR_NUMBER" --repo "$REPO" "${args[@]}"
fi
